// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package mongo

import (
	"clean-arch/internal/adapter/config"
	"context"
	"github.com/google/wire"
)

// Injectors from wire.go:

func Wire(ctx context.Context, cfg *config.Config) (Client, error) {
	mongoClient, err := New(ctx, cfg)
	if err != nil {
		return nil, err
	}
	return mongoClient, nil
}

// wire.go:

var ProviderSet = wire.NewSet(
	New,
)
